"""POST /ai/books/{book_id}/generate — enqueue a BOOK-generate job (V2 slice 2).

These cover the ENQUEUE side of book-level chapter automation: the endpoint must
validate the book + the selected chapters (every chapter belongs to the book;
at least one selected chapter has >=1 generatable scene — EMPTY content AND >=1
beat), persist a PENDING, project-scoped ``book_generate`` job whose
``input_data`` carries the RESOLVED chapter selection (story order), hand its id
to the queue (mocked — no Redis), require auth, and reject bad selections.
"""

import uuid
from unittest.mock import patch

import pytest
from alexandria_core.models.beat import Beat
from alexandria_core.models.book import Book
from alexandria_core.models.chapter import Chapter
from alexandria_core.models.generation_job import GenerationJob, JobStatus, JobType
from alexandria_core.models.project import Project
from alexandria_core.models.scene import Scene
from httpx import AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

# Scene spec: (beat_count, content). content=None → EMPTY scene (generatable
# when beat_count >= 1); a non-empty string → already-written scene (never
# auto-generated by the book job).
SceneSpec = tuple[int, str | None]


async def _make_book(
    db: AsyncSession, *, chapters: list[list[SceneSpec]]
) -> tuple[uuid.UUID, uuid.UUID, list[uuid.UUID]]:
    """project→book→N chapters; ``chapters[i]`` lists that chapter's scene specs.

    Chapters (and scenes) are INSERTED in reverse order but with ascending
    ``order_index`` so any correct resolver must sort by order_index, not by
    insertion/id order. Returns ``(book_id, project_id, [chapter_ids in story
    order])``.
    """
    project = Project(title="Könyv-gen projekt")
    db.add(project)
    await db.flush()
    book = Book(project_id=project.id, title="Könyv")
    db.add(book)
    await db.flush()
    chapter_ids: list[uuid.UUID] = [uuid.uuid4()] * len(chapters)  # placeholder
    for i, scene_specs in reversed(list(enumerate(chapters))):
        chapter = Chapter(book_id=book.id, title=f"Fejezet {i}", order_index=i)
        db.add(chapter)
        await db.flush()
        chapter_ids[i] = chapter.id
        for j, (beat_count, content) in reversed(list(enumerate(scene_specs))):
            scene = Scene(
                chapter_id=chapter.id,
                title=f"Jelenet {i}.{j}",
                order_index=j,
                content=content,
            )
            db.add(scene)
            await db.flush()
            for k in range(beat_count):
                db.add(
                    Beat(
                        scene_id=scene.id,
                        description=f"Beat {i}.{j}.{k}",
                        order_index=k,
                    )
                )
    await db.commit()
    return book.id, project.id, chapter_ids


@pytest.mark.integration
async def test_book_generate_creates_pending_job_and_enqueues(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """Omitted chapter_ids → ALL the book's chapters, in order_index order."""
    book_id, project_id, chapter_ids = await _make_book(
        db_session, chapters=[[(2, None)], [(1, None)]]
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job") as mock_enqueue:
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={"run_continuity": True},
            headers=auth_headers,
        )
    assert resp.status_code == 202, resp.text
    data = resp.json()
    assert data["job_type"] == "book_generate"  # literal — pins the constant
    assert data["job_type"] == JobType.BOOK_GENERATE
    assert data["status"] == JobStatus.PENDING
    assert data["project_id"] == str(project_id)
    # A book job is NOT chapter-scoped.
    assert data["chapter_id"] is None
    # input_data carries the book + the RESOLVED selection in STORY order.
    assert data["input_data"]["book_id"] == str(book_id)
    assert data["input_data"]["chapter_ids"] == [str(c) for c in chapter_ids]
    assert data["input_data"]["run_continuity"] is True

    # Enqueued exactly once with the created job's id.
    mock_enqueue.assert_called_once()
    (enqueued_id,) = mock_enqueue.call_args.args
    assert str(enqueued_id) == data["id"]

    # Persisted as a pending book-generate job for the project.
    job = (
        await db_session.execute(
            select(GenerationJob).where(GenerationJob.id == uuid.UUID(data["id"]))
        )
    ).scalar_one()
    assert job.project_id == project_id
    assert job.job_type == JobType.BOOK_GENERATE
    assert job.status == JobStatus.PENDING


@pytest.mark.integration
async def test_book_generate_job_carries_book_id_and_is_book_scoped(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """The created job carries ``book_id`` as a REAL column (not only inside
    ``input_data``) so the book-scoped jobs listing (`GET /jobs?book_id=`)
    includes book-level jobs — the visibility fix for the AI-feladatok screen."""
    book_id, _project_id, _chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)]]
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job"):
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={},
            headers=auth_headers,
        )
    assert resp.status_code == 202, resp.text
    data = resp.json()
    assert data["book_id"] == str(book_id)

    # Persisted on the row itself.
    job = (
        await db_session.execute(
            select(GenerationJob).where(GenerationJob.id == uuid.UUID(data["id"]))
        )
    ).scalar_one()
    assert job.book_id == book_id

    # And therefore visible on the book-scoped jobs screen.
    listing = await client.get(
        f"/api/v1/jobs?book_id={book_id}", headers=auth_headers
    )
    assert listing.status_code == 200
    assert data["id"] in [j["id"] for j in listing.json()]


@pytest.mark.integration
async def test_book_generate_explicit_subset_is_resolved_in_story_order(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """An explicit chapter selection is stored resolved to STORY (order_index)
    order — even when the request lists it back-to-front."""
    book_id, _project_id, chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)], [(1, None)], [(1, None)]]
    )
    subset = [chapter_ids[2], chapter_ids[0]]  # request order: reversed
    with patch("app.api.v1.ai.enqueue_book_generation_job"):
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={"chapter_ids": [str(c) for c in subset]},
            headers=auth_headers,
        )
    assert resp.status_code == 202, resp.text
    assert resp.json()["input_data"]["chapter_ids"] == [
        str(chapter_ids[0]),
        str(chapter_ids[2]),
    ]


@pytest.mark.integration
async def test_book_generate_persists_model_params(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    book_id, _project_id, _chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)]]
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job"):
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={
                "model": "ollama/llama3.2",
                "temperature": 0.7,
                "max_tokens": 2048,
            },
            headers=auth_headers,
        )
    assert resp.status_code == 202, resp.text
    job = (
        await db_session.execute(
            select(GenerationJob).where(
                GenerationJob.id == uuid.UUID(resp.json()["id"])
            )
        )
    ).scalar_one()
    assert job.input_data["model"] == "ollama/llama3.2"
    assert job.input_data["temperature"] == 0.7
    assert job.input_data["max_tokens"] == 2048
    assert job.input_data["run_continuity"] is False  # defaulted


@pytest.mark.integration
async def test_book_generate_missing_book_is_404(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    with patch("app.api.v1.ai.enqueue_book_generation_job") as mock_enqueue:
        resp = await client.post(
            f"/api/v1/ai/books/{uuid.uuid4()}/generate",
            json={},
            headers=auth_headers,
        )
    assert resp.status_code == 404
    mock_enqueue.assert_not_called()


@pytest.mark.integration
async def test_book_generate_foreign_chapter_is_422(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """A chapter_id belonging to a DIFFERENT book must be rejected (422) and no
    job may leak. Mutation guard for the membership check."""
    book_id, _project_id, chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)]]
    )
    _other_book, _p2, other_chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)]]
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job") as mock_enqueue:
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={
                "chapter_ids": [str(chapter_ids[0]), str(other_chapter_ids[0])]
            },
            headers=auth_headers,
        )
    assert resp.status_code == 422
    mock_enqueue.assert_not_called()
    jobs = (
        (
            await db_session.execute(
                select(GenerationJob).where(
                    GenerationJob.job_type == JobType.BOOK_GENERATE
                )
            )
        )
        .scalars()
        .all()
    )
    assert jobs == []


@pytest.mark.integration
async def test_book_generate_nonexistent_chapter_is_422(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    book_id, _project_id, chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)]]
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job") as mock_enqueue:
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={"chapter_ids": [str(chapter_ids[0]), str(uuid.uuid4())]},
            headers=auth_headers,
        )
    assert resp.status_code == 422
    mock_enqueue.assert_not_called()


@pytest.mark.integration
async def test_book_generate_empty_chapter_list_is_422(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """``chapter_ids: []`` is not a valid selection (null/omitted means ALL)."""
    book_id, _project_id, _chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)]]
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job") as mock_enqueue:
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={"chapter_ids": []},
            headers=auth_headers,
        )
    assert resp.status_code == 422
    mock_enqueue.assert_not_called()


@pytest.mark.integration
async def test_book_generate_nothing_generatable_is_422(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """No selected chapter has any EMPTY scene with beats → 422 with a clear
    message, no job created. Covers both non-generatable shapes: a written scene
    (has content) and an empty scene without beats."""
    book_id, _project_id, _chapter_ids = await _make_book(
        db_session,
        chapters=[[(2, "Már megírt jelenet.")], [(0, None)]],
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job") as mock_enqueue:
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={},
            headers=auth_headers,
        )
    assert resp.status_code == 422
    assert resp.json()["detail"]  # a clear, non-empty message
    mock_enqueue.assert_not_called()
    jobs = (
        (
            await db_session.execute(
                select(GenerationJob).where(
                    GenerationJob.job_type == JobType.BOOK_GENERATE
                )
            )
        )
        .scalars()
        .all()
    )
    assert jobs == []


@pytest.mark.integration
async def test_book_generate_one_generatable_chapter_is_enough(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """A mixed book (one non-generatable + one generatable chapter) is accepted;
    the non-generatable chapter STAYS in the selection (the job records it as
    skipped at runtime)."""
    book_id, _project_id, chapter_ids = await _make_book(
        db_session,
        chapters=[[(1, "Kész jelenet.")], [(1, None)]],
    )
    with patch("app.api.v1.ai.enqueue_book_generation_job"):
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={},
            headers=auth_headers,
        )
    assert resp.status_code == 202, resp.text
    assert resp.json()["input_data"]["chapter_ids"] == [str(c) for c in chapter_ids]


@pytest.mark.integration
async def test_book_generate_requires_auth(
    client: AsyncClient, db_session: AsyncSession
):
    resp = await client.post(f"/api/v1/ai/books/{uuid.uuid4()}/generate", json={})
    assert resp.status_code == 401


@pytest.mark.integration
async def test_book_generate_enqueue_failure_marks_job_failed(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """If enqueue raises (Redis down), the job is persisted FAILED (never stuck
    PENDING) and a sanitized 502 is returned (no broker URL/secret echoed)."""
    book_id, _project_id, _chapter_ids = await _make_book(
        db_session, chapters=[[(1, None)]]
    )
    with patch(
        "app.api.v1.ai.enqueue_book_generation_job",
        side_effect=RuntimeError("redis://:s3cr3t-leak-xyz@broker:6379 refused"),
    ):
        resp = await client.post(
            f"/api/v1/ai/books/{book_id}/generate",
            json={},
            headers=auth_headers,
        )
    assert resp.status_code == 502
    assert "s3cr3t-leak-xyz" not in resp.text
    assert "broker:6379" not in resp.text
    job = (
        await db_session.execute(
            select(GenerationJob).where(
                GenerationJob.job_type == JobType.BOOK_GENERATE
            )
        )
    ).scalar_one()
    assert job.status == JobStatus.FAILED
