/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai/chapters/{chapter_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summarize Chapter */
        post: operations["summarize_chapter_api_v1_ai_chapters__chapter_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/continuity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continuity
         * @description Continuity-check a scene against the project codex (B3).
         *
         *     Returns STRUCTURED warnings (severity / message / entity) — analysis, not
         *     generated content, so there is NO revision. An empty ``warnings`` list is a
         *     positive "no issues found" result.
         *
         *     Degradation contract (no 500 for either case):
         *     - RAG/embeddings unconfigured → the check still runs on the scene text alone
         *       (empty ``context_entities``).
         *     - ``scene_id`` resolves to no scene / empty content → an empty result
         *       (``warnings: []``, ``context_entities: []``), NOT a 404. The UI shows the
         *       positive "no issues" state; there is simply nothing to check.
         */
        post: operations["continuity_api_v1_ai_continuity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/covers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Cover
         * @description Enqueue a cover-generation job for a Book.
         *
         *     Creates a ``generating`` MediaAsset + an IMAGE GenerationJob, hands the job
         *     id to the worker queue, and returns the asset (202). All validation (art_style,
         *     layout, book existence, model availability) happens BEFORE anything is created
         *     and OUTSIDE the try, so a 422 is never re-wrapped into a 502.
         */
        post: operations["generate_cover_api_v1_ai_covers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/covers/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cover Layouts
         * @description List the available cover typography layouts.
         */
        get: operations["list_cover_layouts_api_v1_ai_covers_layouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/covers/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cover Styles
         * @description List the available cover art-style presets.
         */
        get: operations["list_cover_styles_api_v1_ai_covers_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/describe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Describe */
        post: operations["describe_api_v1_ai_describe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/generate-scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Scene */
        post: operations["generate_scene_api_v1_ai_generate_scene_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Images
         * @description List an entity's generated images, newest-first.
         *
         *     Both ``entity_type`` and ``entity_id`` are required query params (FastAPI
         *     returns 422 when either is missing).
         */
        get: operations["list_images_api_v1_ai_images_get"];
        put?: never;
        /**
         * Create Image
         * @description Enqueue an image-generation job for a Codex entry (character/location).
         *
         *     Creates a ``generating`` MediaAsset + an IMAGE GenerationJob, hands the job
         *     id to the worker queue, and returns the asset (202). Poll ``GET /jobs/{id}``
         *     (the worker flips the asset to ready/failed). All validation (entity_type,
         *     style, project existence, the referenced CodexEntry, model availability)
         *     happens BEFORE anything is created and OUTSIDE the try, so a 422 is never
         *     re-wrapped into a 502.
         */
        post: operations["create_image_api_v1_ai_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/images/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Styles
         * @description List the available image-prompt style presets for an entity type.
         */
        get: operations["list_styles_api_v1_ai_images_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/images/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Image
         * @description Delete an image (row + files).
         */
        delete: operations["delete_image_api_v1_ai_images__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/images/{asset_id}/canonical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Canonical
         * @description Mark an image canonical (clears the flag on the entity's other images).
         */
        post: operations["set_canonical_api_v1_ai_images__asset_id__canonical_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index Project
         * @description Re-index a project's RAG content (Codex + manuscript).
         *
         *     ``project_id`` may be given as a query param (preferred) or in the body.
         *     When no embedding provider is configured, RAG is unconfigured: this returns
         *     zeroed counts with ``skipped_no_provider=True`` (a 200, not an error — cloud
         *     embeddings are optional).
         */
        post: operations["index_project_api_v1_ai_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/index/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index Project Async
         * @description Enqueue an async project RAG re-index onto the worker queue.
         *
         *     Returns the queued ``GenerationJob`` (status ``pending``) immediately;
         *     poll ``GET /jobs/{id}`` for progress (the worker flips it to running →
         *     done/failed and writes the index counts into ``output_data``). The worker
         *     resolves the embedding provider — when none is configured the job completes
         *     as a no-op (``output_data.skipped_no_provider = true``), never an error.
         *
         *     ``project_id`` may be given as a query param (preferred) or in the body.
         *     If the queue cannot be reached, the job is marked failed (so it never
         *     dangles as forever-pending) and a sanitized 502 is returned.
         */
        post: operations["index_project_async_api_v1_ai_index_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/media/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Media
         * @description Stream a ready image's binary. ``?thumb=1`` serves the thumbnail.
         *
         *     AUTH: header-only (``Authorization: Bearer``), same as every other endpoint.
         *     The frontend fetches this binary with the JWT in the header and renders it
         *     via an object URL, so the token NEVER appears in a URL/query string (no
         *     secret-in-URL/log leakage).
         *
         *     TRAVERSAL SAFETY: only the path STORED on the DB row is served (never a
         *     client-supplied path), and the resolved real path is additionally verified to
         *     live inside ``settings.media_dir`` — anything outside is refused as a 404, so
         *     a tampered row can never exfiltrate an arbitrary file.
         */
        get: operations["serve_media_api_v1_ai_media__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return the AI models the backend is configured to use.
         *
         *     Aggregated from the configured + enabled Provider rows (local Ollama + any
         *     cloud providers). The built-in Ollama default from settings is always
         *     included so the app works out of the box with no providers configured. Model
         *     names are never hardcoded in the UI — it reads them from here.
         */
        get: operations["list_models_api_v1_ai_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Research
         * @description Answer a free-form question grounded on the project's Codex + manuscript
         *     (RAG Q&A). Analysis only — NO revision, nothing is written to the manuscript.
         *
         *     Degradation contract (no 500 for either case):
         *     - empty/whitespace question → empty answer + empty context_entities.
         *     - RAG/embeddings unconfigured → the model still answers from the question
         *       alone (empty context_entities), never an error.
         */
        post: operations["research_api_v1_ai_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/rewrite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rewrite */
        post: operations["rewrite_api_v1_ai_rewrite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/scenes/{scene_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summarize Scene */
        post: operations["summarize_scene_api_v1_ai_scenes__scene_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/write-continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Continue */
        post: operations["write_continue_api_v1_ai_write_continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_v1_providers_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_api_v1_providers__provider_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_providers__provider_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_providers__provider_id__patch"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_providers__provider_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/models/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pull
         * @description Download (pull) an Ollama model, streaming NDJSON progress to the client.
         *
         *     Only valid for a local Ollama provider (others → 400). Progress is streamed
         *     verbatim from Ollama: one JSON object per line, ending with
         *     ``{"status": "success"}``. If Ollama is unreachable / errors before the
         *     first byte, an actionable 502/503 is returned instead of a broken stream.
         */
        post: operations["pull_api_v1_providers__provider_id__models_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_api_v1_providers__provider_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIDescribeResult */
        AIDescribeResult: {
            /** Context Entities */
            context_entities?: components["schemas"]["ContextEntity"][];
            job: components["schemas"]["GenerationJobRead"];
            /** Revisions */
            revisions: components["schemas"]["RevisionRead"][];
        };
        /** AIResult */
        AIResult: {
            /** Context Entities */
            context_entities?: components["schemas"]["ContextEntity"][];
            job: components["schemas"]["GenerationJobRead"];
            revision: components["schemas"]["RevisionRead"];
        };
        /**
         * ContextEntity
         * @description A Codex/manuscript entry that RAG injected into the generation context.
         *
         *     Lets the UI show "grounded on: <these entries>". Empty whenever RAG was
         *     skipped (no scene_id, no embedding provider configured) or found nothing.
         */
        ContextEntity: {
            /** Entity Type */
            entity_type: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ContinuityRequest */
        ContinuityRequest: {
            /** Max Tokens */
            max_tokens?: number | null;
            /** Model */
            model?: string | null;
            /**
             * Scene Id
             * Format: uuid
             */
            scene_id: string;
            /** Temperature */
            temperature?: number | null;
        };
        /**
         * ContinuityResult
         * @description Continuity-check response (B3). NO revision — this is analysis.
         *
         *     ``warnings`` is empty when no issues were found (a positive "all clear").
         *     ``context_entities`` lists the codex entries RAG grounded the check on (empty
         *     when RAG was skipped / unconfigured — the check then ran on the scene text
         *     alone).
         */
        ContinuityResult: {
            /** Context Entities */
            context_entities?: components["schemas"]["ContextEntity"][];
            /** Warnings */
            warnings?: components["schemas"]["ContinuityWarning"][];
        };
        /**
         * ContinuityWarning
         * @description One structured continuity finding (B3).
         *
         *     ``severity`` is one of info/warning/error (validated + clamped service-side,
         *     but kept a free ``str`` on the wire so a future severity still renders).
         *     ``message`` is the Hungarian description; ``entity`` is the affected Codex
         *     entity name, or ``None``.
         */
        ContinuityWarning: {
            /** Entity */
            entity?: string | null;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
        };
        /** CoverGenerateRequest */
        CoverGenerateRequest: {
            /** Art Style */
            art_style: string;
            /** Author */
            author?: string | null;
            /**
             * Book Id
             * Format: uuid
             */
            book_id: string;
            /** Layout */
            layout: string;
            /** Model */
            model?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title?: string | null;
        };
        /** CoverLayoutInfo */
        CoverLayoutInfo: {
            /** Label */
            label: string;
            /** Slug */
            slug: string;
        };
        /** DescribeRequest */
        DescribeRequest: {
            /** Channels */
            channels?: string[] | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Model */
            model?: string | null;
            /** Scene Id */
            scene_id?: string | null;
            /** Selected Text */
            selected_text: string;
            /** Temperature */
            temperature?: number | null;
        };
        /** GenerateSceneRequest */
        GenerateSceneRequest: {
            /** Beats */
            beats: string[];
            /**
             * Characters
             * @default
             */
            characters: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Model */
            model?: string | null;
            /** Scene Id */
            scene_id?: string | null;
            /**
             * Style Notes
             * @default
             */
            style_notes: string;
            /** Temperature */
            temperature?: number | null;
        };
        /** GenerationJobRead */
        GenerationJobRead: {
            /** Chapter Id */
            chapter_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Data */
            input_data: {
                [key: string]: unknown;
            } | null;
            /** Job Type */
            job_type: string;
            /** Model Name */
            model_name: string | null;
            /** Output Data */
            output_data: {
                [key: string]: unknown;
            } | null;
            /** Project Id */
            project_id: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Scene Id */
            scene_id: string | null;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageGenerateRequest
         * @description Enqueue an image-generation job for a Codex entity.
         */
        ImageGenerateRequest: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Model */
            model?: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Style */
            style: string;
        };
        /**
         * ImageStyleInfo
         * @description A selectable image-prompt style preset.
         */
        ImageStyleInfo: {
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
            /** Slug */
            slug: string;
        };
        /** IndexRequest */
        IndexRequest: {
            /** Project Id */
            project_id?: string | null;
        };
        /**
         * IndexResult
         * @description Summary returned by ``POST /ai/index`` (project re-index).
         */
        IndexResult: {
            /** Capped */
            capped: boolean;
            /** Deleted */
            deleted: number;
            /** Indexed */
            indexed: number;
            /** Skipped */
            skipped: number;
            /**
             * Skipped No Provider
             * @default false
             */
            skipped_no_provider: boolean;
            /** Updated */
            updated: number;
        };
        /**
         * MediaAssetRead
         * @description Client view of a generated image. NO file_path/thumb_path (the client
         *     builds the URL from ``id``).
         */
        MediaAssetRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id: string | null;
            /** Entity Type */
            entity_type: string;
            /** Height */
            height: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Canonical */
            is_canonical: boolean;
            /** Mime */
            mime: string;
            /** Model Name */
            model_name: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Status */
            status: string;
            /** Style */
            style: string | null;
            /** Width */
            width: number | null;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /**
             * Moderated
             * @default false
             */
            moderated: boolean;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /** Default */
            default: string;
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Image Model */
            image_model?: string | null;
            /** Label */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "ollama" | "gemini" | "anthropic" | "openai" | "openrouter" | "custom";
        };
        /** ProviderModelInfo */
        ProviderModelInfo: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ProviderModelsResult */
        ProviderModelsResult: {
            /** Models */
            models: components["schemas"]["ProviderModelInfo"][];
        };
        /**
         * ProviderPullRequest
         * @description Request body for ``POST /providers/{id}/models/pull``.
         *
         *     ``model`` is interpolated into the Ollama ``/api/pull`` JSON body, so there
         *     is no injection surface, but we still cap length and restrict the charset to
         *     a sane Ollama tag (``namespace/name:tag``) — letters, digits and the small
         *     set of separators Ollama model refs use. This rejects whitespace/control
         *     chars and pathologically long input at the schema boundary (422).
         */
        ProviderPullRequest: {
            /** Model */
            model: string;
        };
        /**
         * ProviderRead
         * @description Safe read view of a provider.
         *
         *     Deliberately exposes ONLY a masked key + a ``has_key`` flag. The plaintext
         *     api_key and the stored ciphertext (api_key_encrypted) are NEVER present here.
         */
        ProviderRead: {
            /** Api Key Masked */
            api_key_masked: string | null;
            /** Base Url */
            base_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Model */
            default_model: string | null;
            /** Embedding Model */
            embedding_model: string | null;
            /** Enabled */
            enabled: boolean;
            /** Has Key */
            has_key: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Model */
            image_model: string | null;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProviderTestResult */
        ProviderTestResult: {
            /** Detail */
            detail: string;
            /** Ok */
            ok: boolean;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Image Model */
            image_model?: string | null;
            /** Label */
            label?: string | null;
            /** Type */
            type?: ("ollama" | "gemini" | "anthropic" | "openai" | "openrouter" | "custom") | null;
        };
        /**
         * ResearchRequest
         * @description A free-form Codex/manuscript Q&A question, grounded via RAG (P2).
         */
        ResearchRequest: {
            /** Max Tokens */
            max_tokens?: number | null;
            /** Model */
            model?: string | null;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Question */
            question: string;
            /** Scene Id */
            scene_id?: string | null;
            /** Temperature */
            temperature?: number | null;
        };
        /**
         * ResearchResult
         * @description Codex/manuscript Q&A response (P2). NO revision — this is analysis.
         *
         *     ``answer`` is the model's grounded answer (empty only for an empty question).
         *     ``context_entities`` lists the Codex/manuscript entries RAG grounded the
         *     answer on (empty when RAG was skipped / unconfigured — the model then answered
         *     from the question alone), shown as citation chips.
         */
        ResearchResult: {
            /**
             * Answer
             * @default
             */
            answer: string;
            /** Context Entities */
            context_entities?: components["schemas"]["ContextEntity"][];
        };
        /**
         * RevisionRead
         * @description Read view of a Revision.
         *
         *     Shared because two services produce/consume it across the service boundary:
         *     ``apps/ai`` creates Revisions from AI output and returns them; ``apps/api``
         *     lists them and applies the human-in-the-loop approve/reject (mutating Scene).
         *     Both read the same shared Postgres rows, so the contract lives here.
         */
        RevisionRead: {
            /** Approved */
            approved: boolean;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Id */
            job_id: string | null;
            /** Model Name */
            model_name: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Revision Type */
            revision_type: string;
            /** Scene Id */
            scene_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RewriteRequest */
        RewriteRequest: {
            /** Instruction */
            instruction: string;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Model */
            model?: string | null;
            /** Scene Id */
            scene_id?: string | null;
            /** Selected Text */
            selected_text: string;
            /** Temperature */
            temperature?: number | null;
        };
        /** SummarizeRequest */
        SummarizeRequest: {
            /** Chapter Id */
            chapter_id?: string | null;
            /** Content */
            content: string;
            /**
             * Content Type
             * @default jelenet
             */
            content_type: string;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Model */
            model?: string | null;
            /** Scene Id */
            scene_id?: string | null;
            /** Temperature */
            temperature?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WriteContinueRequest */
        WriteContinueRequest: {
            /**
             * Context
             * @default
             */
            context: string;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Model */
            model?: string | null;
            /** Scene Id */
            scene_id?: string | null;
            /** Scene Text */
            scene_text: string;
            /** Temperature */
            temperature?: number | null;
            /**
             * Word Count Target
             * @default 300
             */
            word_count_target: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    summarize_chapter_api_v1_ai_chapters__chapter_id__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continuity_api_v1_ai_continuity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinuityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContinuityResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_cover_api_v1_ai_covers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cover_layouts_api_v1_ai_covers_layouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverLayoutInfo"][];
                };
            };
        };
    };
    list_cover_styles_api_v1_ai_covers_styles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageStyleInfo"][];
                };
            };
        };
    };
    describe_api_v1_ai_describe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DescribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIDescribeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_scene_api_v1_ai_generate_scene_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSceneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_api_v1_ai_images_get: {
        parameters: {
            query: {
                entity_type: string;
                entity_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_image_api_v1_ai_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_styles_api_v1_ai_images_styles_get: {
        parameters: {
            query: {
                entity_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageStyleInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_v1_ai_images__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_canonical_api_v1_ai_images__asset_id__canonical_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_project_api_v1_ai_index_post: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IndexRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_project_async_api_v1_ai_index_async_post: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IndexRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_media_api_v1_ai_media__asset_id__get: {
        parameters: {
            query?: {
                thumb?: number;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_ai_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    research_api_v1_ai_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_api_v1_ai_rewrite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_scene_api_v1_ai_scenes__scene_id__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_continue_api_v1_ai_write_continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteContinueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_v1_jobs_get: {
        parameters: {
            query?: {
                scene_id?: string | null;
                status?: string | null;
                book_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_v1_providers_get: {
        parameters: {
            query?: {
                enabled_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_api_v1_providers__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_providers__provider_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_providers__provider_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_api_v1_providers__provider_id__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderModelsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_api_v1_providers__provider_id__models_pull_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderPullRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_v1_providers__provider_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
